# Generated by Django 4.2.1 on 2023-06-06 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_key', models.JSONField(blank=True, null=True)),
                ('height', models.IntegerField()),
                ('choices', models.IntegerField()),
                ('max_q', models.IntegerField()),
                ('max_mark', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preview.preview')),
            ],
        ),
    ]
