# Generated by Django 4.2.1 on 2023-06-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grader',
            old_name='preview_id',
            new_name='preview',
        ),
    ]
