# Generated by Django 4.2.1 on 2023-05-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grader',
            name='answer_key',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='grader',
            name='optimized_dir',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
